# Generated by Django 4.2.7 on 2024-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='addressLine1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='addressLine2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='gameCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
